package com.forger.fofa;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import jdk.internal.dynalink.support.NameCodec;
import sun.misc.BASE64Encoder;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;

public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Fofa_Email:");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));

        jLabel2.setText("Search:");

        jLabel3.setText("Api_Key:");

        jTextField1.setText("");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField3.setText("domain=\"baidu.com\"");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "50", "100", "500", "1000", "5000", "10000" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Num:");

        jButton2.setText("clean&help");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                help,
                new String [] { "Search例句", "用途说明", "注"}
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton3.setText("采集");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPasswordField1.setText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel2)
                                                                .addGap(34, 34, 34)
                                                                .addComponent(jTextField3))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel1)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, true)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel4)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(102, 102, 102)
                                                                .addComponent(jButton3)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jButton2))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel3)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jPasswordField1)))))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton2)
                                        .addComponent(jButton3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                help,
                new String [] { "Search例句", "用途说明", "注"}
        ));
    }

    private void jButton3ActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
        //base64编码器
        BASE64Encoder base64Encoder = new BASE64Encoder();
        //传入获取数据的方法
        getGetDateByDomain doGetData = new getGetDateByDomain();
        //获取email信息
        String email = jTextField1.getText();
        //获取api_key
        String api_key = jPasswordField1.getText();
        //获取搜索内容
        String search = jTextField3.getText();
        byte[] textDomain = search.getBytes();
        String b64domain = base64Encoder.encode(textDomain);
        //获取查询数量num
        String num = jComboBox1.getSelectedItem().toString().trim();
        //通过api接口获取查询内容
        try {
            String fofaResultData = doGetData.getDataByUrl(email, api_key, b64domain, num);
            //只取result的值
            String[] filterData = fofaResultData.split("results\":");
            String resultData = filterData[1].replace("}", "").replace("[", "{")
                    .replace("]", "}");

            System.out.println(resultData);

            //处理resultData是string类型无法传入表格的问题
            String[] s1 = resultData.split("},\\{");
            int len = s1[0].split("\",\"").length;
            String[][] arr1 = new String[s1.length][len];
            for (int i = 0; i < s1.length; i++) {
                String tmp = s1[i].replaceAll("\\}", "");
                String tmp2 = tmp.replaceAll("\\{", "");
                String[] split = tmp2.split("\",\"");
                for (int j = 0; j < split.length; j++) {
                    arr1[i][j]=split[j].replace("\"", "");
                }
            }
            jTable1.setModel(new javax.swing.table.DefaultTableModel(
                    arr1,
                    new String [] { "域名", "PORT", "STATUS", "BANNER", "IP","SERVER"}
            ));
            jTable1.getColumnModel().getColumn(1).setMaxWidth(50);
            jScrollPane1.setViewportView(jTable1);
        } catch (Exception exception) {
            exception.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame fofa_JFrame = new NewJFrame();
                fofa_JFrame.setTitle("Fofa信息采集工具 V1.0 by Forger");
                fofa_JFrame.setVisible(true);
                fofa_JFrame.setSize(new Dimension(780, 800));
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration

    //增加默认表格帮助数据
    Object [][] help = {
            {"title=\"beijing\"", "从标题中搜索\"北京\"", "-"},
            {"header=\"jboss\"", "从http头中搜索\"jboss\"", "-"},
            {"body=\"Hacked by\"", "从html正文中搜索abc", "-"},
            {"domain=\"qq.com\"", "搜索根域名带有qq.com的网站", "-"},
            {"icon_hash=\"-247388890\"", "搜索使用此icon的资产", "仅限高级会员使用"},
            {"host=\".gov.cn\"", "从url中搜索\".gov.cn\"", "搜索要用host作为名称"},
            {"port=\"443\"", "查找对应\"443\"端口的资产", "-"},
            {"ip=\"1.1.1.1\"", "从ip中搜索包含\"1.1.1.1\"的网站", "搜索要用ip作为名称"},
            {"ip=\"220.181.111.1/24\"", "查询IP为\"220.181.111.1\"的C网段资产", "-"},
            {"status_code=\"402\"", "查询服务器状态为\"402\"的资产", "-"},
            {"protocol=\"https\"", "查询https协议资产", "搜索指定协议类型(在开启端口扫描的情况下有效)"},
            {"city=\"Hangzhou\"", "搜索指定城市的资产", "-"},
            {"region=\"Zhejiang\"", "搜索指定行政区的资产", "-"},
            {"country=\"CN\"", "搜索指定国家(编码)的资产", "-"},
            {"cert=\"google\"", "搜索证书(https或者imaps等)中带有google的资产", "-"},
            {"banner=users && protocol=ftp", "搜索FTP协议中带有users文本的资产", "-"},
            {"type=service", "搜索所有协议资产", "支持subdomain和service两种", "搜索所有协议资产"},
            {"os=windows", "搜索Windows资产", "-"},
            {"server==\"Microsoft-IIS/7.5\"", "搜索IIS 7.5服务器", "-"},
            {"app=\"HIKVISION-视频监控\"", "搜索海康威视设备", "-"},
            {"after=\"2017\" && before=\"2017-10-01\"", "时间范围段搜索", "-"},
            {"asn=\"19551\"", "搜索指定asn的资产", "-"},
            {"org=\"Amazon.com", " Inc.\"", "搜索指定org(组织)的资产", "-"},
            {"base_protocol=\"udp\"", "搜索指定udp协议的资产", "-"},
            {"is_ipv6=true", "搜索ipv6的资产", "搜索ipv6的资产, 只接受true和false"},
            {"is_domain=true", "搜索域名的资产", "搜索域名的资产, 只接受true和false"},
            {"ip_ports=\"80", "161\"", "搜索同时开放80和161端口的ip", "搜索同时开放80和161端口的ip资产(以ip为单位的资产数据)"},
            {"port_size=\"6\"", "查询开放端口数量等于\"6\"的资产", "仅限FOFA会员使用"},
            {"port_size_gt=\"3\"", "查询开放端口数量大于\"3\"的资产", "仅限FOFA会员使用"},
            {"port_size_lt=\"12\"", "查询开放端口数量小于\"12\"的资产", "仅限FOFA会员使用"},
            {"ip_country=\"CN\"", "搜索中国的ip资产(以ip为单位的资产数据)", "搜索中国的ip资产"},
            {"ip_region=\"Zhejiang\"", "搜索指定行政区的ip资产(以ip为单位的资产数据)", "搜索指定行政区的资产"},
            {"ip_city=\"Hangzhou\"", "搜索指定城市的ip资产(以ip为单位的资产数据)", "搜索指定城市的资产"},
            {"ip_after=\"2019-01-01\"", "搜索2019-01-01以后的ip资产(以ip为单位的资产数据)", "搜索2019-01-01以后的ip资产"},
            {"ip_before=\"2019-07-01\"", "搜索2019-07-01以前的ip资产(以ip为单位的资产数据)", "搜索2019-07-01以前的ip资产"}
    };
}

